name: Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, sqlite3, bcmath, gd

    - name: Copy .env
      run: |
        cp .env.example .env.test
        echo "APP_ENV=testing" >> .env.test
        echo "DB_CONNECTION=sqlite" >> .env.test
        echo "DB_DATABASE=:memory:" >> .env.test
        echo "CACHE_DRIVER=array" >> .env.test
        echo "SESSION_DRIVER=array" >> .env.test
        echo "QUEUE_CONNECTION=sync" >> .env.test

    - name: Install Dependencies
      run: |
        composer install --no-interaction --prefer-dist
        php artisan key:generate --env=testing

    - name: Run Migrations
      run: php artisan migrate --env=testing

    - name: Execute tests
      run: vendor/bin/phpunit